// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5gY5D3R7LljlsG21eFKl13aXnTBnDxQ',
    appId: '1:1096324764309:web:fac1a666f38711315b419c',
    messagingSenderId: '1096324764309',
    projectId: 'e-shop-ee3d0',
    authDomain: 'e-shop-ee3d0.firebaseapp.com',
    storageBucket: 'e-shop-ee3d0.appspot.com',
    measurementId: 'G-8MM4JLBCL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMNL2UrrmZB59oGqNxPeByTHU3uJJXeU',
    appId: '1:1096324764309:android:d59e3c336653fe685b419c',
    messagingSenderId: '1096324764309',
    projectId: 'e-shop-ee3d0',
    storageBucket: 'e-shop-ee3d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23jroNi2RCh9x4wjLT2b1A-sMebGHUYE',
    appId: '1:1096324764309:ios:b4da5c53d483d9385b419c',
    messagingSenderId: '1096324764309',
    projectId: 'e-shop-ee3d0',
    storageBucket: 'e-shop-ee3d0.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc5gY5D3R7LljlsG21eFKl13aXnTBnDxQ',
    appId: '1:1096324764309:web:341dfa35d08f56cb5b419c',
    messagingSenderId: '1096324764309',
    projectId: 'e-shop-ee3d0',
    authDomain: 'e-shop-ee3d0.firebaseapp.com',
    storageBucket: 'e-shop-ee3d0.appspot.com',
    measurementId: 'G-ZPNV4NPWJ5',
  );
}
